import "ConnectionViewModel.idl";

namespace blurt {

[default_interface]
runtimeclass MainPage : Windows.UI.Xaml.Controls.Page {
    MainPage();
    ConnectionViewModel MainViewModel { get; };
}

}  // namespace blurt
